const fs = require('fs');

function runEvaluation() {
  const oosFile = 'server/data/backtests/bt_OOS.json';
  const data = JSON.parse(fs.readFileSync(oosFile));
  
  let grossPnL = 0;
  for(let r of data) { grossPnL += r.netPnL_at_24h_Pct; }
  
  console.log(`=== OOS RAW BASELINE ===`);
  console.log(`Total Trades generated by momentum score: ${data.length}`);
  console.log(`Raw PnL (No TP/SL): ${grossPnL.toFixed(2)}%`);
}

runEvaluation();
